version: "2"
run:
  build-tags:
    - integration
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - godot
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    nolintlint:
      require-explanation: true
      require-specific: true
    revive:
      rules:
        - name: comment-spacings
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - blank
        - dot
        - prefix(k8s.io,sigs.k8s.io)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
